version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: konsus
      MYSQL_PASSWORD: konsus
      MYSQL_ROOT_PASSWORD: konsus
      MYSQL_DATABASE: superstock
      MYSQL_ROOT_HOST: '%'